name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '5.0.301'

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest #containerized actions must run on ubunti-latest (https://docs.microsoft.com/en-us/dotnet/devops/create-dotnet-github-action)

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run HTTP server
      uses: actions/devops-challenge-dotnet@v1 #my action

    - name: Test
      run: dotnet test --no-restore --verbosity normal